### ISSUE TITLE
💡 [REQUEST] - <Compact View Synced Lyrics>

### ISSUE THREAD

**Issue by GitGitu79** [boidushya/better-lyrics#71]
### Summary

Basically instead of the full lyrics scrolling down, it's one line at a time appearing.

It's like how Musixmatch have a compact mode to view synced lyrics one line at a time.

### Basic Example

![Screenshot_20241005_214456_Apple Music](https://github.com/user-attachments/assets/410481df-9068-416e-b290-b7777eefdf5a)

### Would you like to work on this feature?

- [ ] I would like to work on this feature

**Comment by boidushya** [comment]
This is already possible with custom CSS! Here's a snippet to achieve this (building on top of Even Better Lyrics, a theme by Noah)

```css
/* Even Better Lyrics, a theme for BetterLyrics by Noah  */

:root {
  --yt-album-size: 500px;
  --blyrics-hover-scale: 1.02;
  /* Existing root variables... */
}

ytmusic-player-page:not([video-mode]):not([player-fullscreened]):not([blyrics-dfs]):not([player-ui-state="MINIPLAYER"]) #player.ytmusic-player-page {
  max-width: var(--yt-album-size) !important;
  overflow: hidden;
}

.blyrics-container {
  overflow: hidden;
  padding: 10px;
}

.blyrics-container:has(.blyrics--active) > div:not(.blyrics--active):not(.blyrics--active ~ div) {
  opacity: 0;
  filter: blur(2.5px);
}

.blyrics-container > div.blyrics--active {
  opacity: 1;
  filter: blur(0px);
}

.blyrics-container > div.blyrics--active ~ div {
  opacity: 0;
  filter: blur(0px);
}

.blyrics-container > div {
  transition: filter calc(var(--blyrics-duration) / 2), opacity calc(var(--blyrics-duration) / 2), transform 0.166s;
  padding: 5px 0;
  transform-origin: left center;
}

/* Refined hover effect for lyrics */
.blyrics-container > div:hover {
  opacity: 1 !important;
  filter: blur(0px) !important;
  transform: scale(var(--blyrics-hover-scale));
  transition: all 0.3s ease;
}

```
